---
title: "Zero to Quarto Workshop"
subtitle: "Build your first quarto website (or something other cool things!)"
format: 
  html:
    toc: true
    toc-depth: 2
    linestretch: 1.7
---

Date: Monday 23 October 2023, 6:30PM to 8:00PM, CEST 

Place: KO2-F-153, Rämistrasse 71, Zürich.

[Event link](https://www.meetup.com/rladies-zurich/events/296330423/)

Presenter: [Chi Zhang](https://andreaczhang.github.io). Feel free to reach out with comments and feedback!

------------------
 
# Welcome!

Quarto is one of the most discussed topics in the R community for the past year. In the posit conf 2023 that just happened a few weeks ago, there were 23 (!) talks on this open-source publishing system. You can build a personal or organisation website; a course or workshop website; a blog; a scientific report; a presentation; all with the possibility to display and execute code (R, Python, Julia), and for free.


If you:

* don't know what quarto is yet, and want to find out more
* heard of quarto somewhere, but don't know where to start
* are an expert in quarto and want to share your experience

then this workshop is for you!


### Pre-requisites & technical setup

No prior quarto experience is needed. 

Good to know:

* some **markdown** 
* some **git**
* some **r**

Please check out [this page](setup.qmd) for how to set up your laptop and GitHub.


### Plan for today

|     Time         |           Topic                |
|:----------------:|:------------------------------:|
|  18:00 - 18:30   | Set up your laptop  |
|  18:30 - 18:40   | Welcome and ice-breaker questions  |
|  18:45 - 19:30   | **Workshop** |
|  19:30 onwards   | Socializing |

